name: Docs
on: 
  workflow_run:
    workflows: [Ceedling Testing]
    types: [completed]
jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Current Repo Clone
        uses: actions/checkout@v4
      - name: Install  build-essential
        run: sudo apt-get install -y -qq build-essential
      - name: Install Doxygen
        run: sudo apt-get install -y -qq doxygen
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install Ceedling
        run: gem install ceedling
      - name: Install GCOVR
        run: sudo apt-get install -y -qq gcovr
      - name: Run Coverage
        run: |
          CUR=$PWD; 
          for i in `find . -type d -name 'ceedling'`; do cd $CUR; P=${i%ceedling}; echo $P; mkdir -p $CUR/gh-pages/$P; cd $i; ceedling gcov:all utils:gcov; cp -r build/artifacts/gcov $CUR/gh-pages/$P; mv $CUR/gh-pages/$P/gcov/GcovCoverageResults.html $CUR/gh-pages/$P/gcov/index.html; done
      - name: Create Doxygen documentation
        run: |
          CUR=$PWD; 
          for i in `find . -name Doxyfile -type f`; do P=`dirname $i`; mkdir -p gh-pages/$P; cd $P; doxygen; sed -i -e 's.<tt>..g' docs/html/navtreedata.js; sed -i -e 's.</tt>..g' docs/html/navtreedata.js; cp -r docs/html $CUR/gh-pages/$P/doxygen; cd $CUR; done
      - name: Create index files
        run: |
          cd gh-pages; 
          CUR=$PWD; 
          for f in `find . -type d`; do cd $CUR; cd $f; if test -f index.html; then echo "index.html exists in $f"; else for i in `ls`; do echo "<a href=\"$i/index.html\">$i</a></br>" >> index.html; done; fi; cd $CUR; done
      - name: Deploy to GitHub pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          BRANCH: gh-pages
          FOLDER: gh-pages
